export const cities = [
  'Dallas',
  'Fort Worth',
  'Arlington',
  'Plano',
  'Garland',
  'Irving',
  'Grand Prairie',
  'McKinney',
  'Mesquite',
  'Frisco',
  'Waco',
  'Carrollton',
  'Denton',
  'Richardson',
  'Lewisville',
  'Allen',
  'Flower Mound',
  'North Richland Hills',
  'Mansfield',
  'Rowlett',
  'Euless',
  'DeSoto',
  'Grapevine',
  'Bedford',
  'Cedar Hill',
  'Wylie',
  'Keller',
  'Coppell',
  'Rockwall',
  'Duncanville',
  'Sherman',
  'The Colony',
  'Burleson',
  'Hurst',
  'Lancaster'
]

export const placements = [
  'Driveway (Front or side Entrance of Street)',
  'Driveway (Back or side Entrance of Alley)',
  'Behind Building',
  'Front of Building',
  'Inside Warehouse or Garage',
  'in Yard',
  'Other'
]
